#!/usr/bin/bash
set -Eeuo pipefail

apply_file() {
    local source=$1 destination=$2 temporary="${2}.bifrost-new"
    install -d -m 0755 "${destination%/*}"
    install -m 0644 "$source" "$temporary"
    mv -f -- "$temporary" "$destination"
}

apply_file /usr/share/bifrost/branding/cosmic-background.ron \
    /usr/share/cosmic/com.system76.CosmicBackground/v1/all
apply_file /usr/share/bifrost/branding/plymouthd.conf \
    /etc/plymouth/plymouthd.conf
